server:
  port: 8700
uri:
  api:
    clientes: http://localhost:8080
    employees: http://localhost:8081

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestTokens: 1
        - name: CircuitBreaker
          args:
            name: clienteService
            fallbackUri: fordward:/service-fallback
      routes:
        - id: clientes_by_id
          uri: http://localhost:8080
          predicates:
            - Path=/promerica/v1/api/cliente-por-id/{id}
          filters:
            - RewritePath=/promerica/v1/api/cliente-por-id/, /v1/api/cliente/id/
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER, GATEWAY_REQUEST
            - AddResponseHeader=X-GATEWAY-RESPONSE-HEADER, GATEWAY_RESPONSE
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
# Trace every action
management:
  tracing:
    sampling:
      probability: 1.0




